export interface Article {
  id: number;
  cat: string;
  title: string;
  excerpt: string;
  body: string;
  author: string;
  date: string;
  readTime: string;
  type: "article" | "photo" | "video" | "interview";
}

export const articles: Article[] = [
  {
    id: 1,
    cat: "EXCLUSIVE",
    title: "Inside the Private World of Hollywood's Most Elusive A-Lister",
    excerpt: "An intimate look at the life, career, and untold stories behind one of cinema's biggest names.",
    body: "Placeholder body — full content will be generated by subagent.",
    author: "Robert Pham",
    date: "Jul 14, 2026",
    readTime: "8 min",
    type: "article",
  },
];
